export const menu = [
  {
    title: "components",
    items: [
      { title: "Button", href: "/button" },
      { title: "Icon Button", href: "/icon-button" },
      { title: "Input", href: "/input" },
      { title: "Select", href: "/select" },
      { title: "Checkbox", href: "/checkbox" },
      { title: "Radio Group", href: "/radio-group" },
      { title: "Date Picker", href: "/date-picker" },
      { title: "Switch", href: "/switch" },
      { title: "Textarea", href: "/textarea" },
      { title: "Chip", href: "/chip" },
      { title: "Avatar", href: "/avatar" },
      { title: "Dialog", href: "/dialog" },
      { title: "Bottom Sheet", href: "/bottom-sheet" },
      { title: "Badge", href: "/badge" },
      { title: "Skeleton", href: "/skeleton" },
      { title: "Dropdown Menu", href: "/dropdown-menu" },
      { title: "Popover", href: "/popover" },
      { title: "Tooltip", href: "/tooltip" },
      { title: "Form", href: "/form" },
      { title: "Board", href: "/board" },
      { title: "Settings", href: "/settings" },
    ],
  },
  {
    title: "mobile",
    items: [
      { title: "Apartments", href: "/apartments" },
      { title: "Permissions", href: "/permissions" },
    ],
  },
] as const;
