import "@/styles/globals.css";

import { Header } from "@/components/layouts/header";
import { Sidebar } from "@/components/layouts/sidebar";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Providers } from "./providers";

const pretendard = localFont({
  src: [
    {
      path: "../assets/fonts/Pretendard-Regular.subset.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/Pretendard-Medium.subset.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/Pretendard-SemiBold.subset.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../assets/fonts/Pretendard-Bold.subset.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../assets/fonts/Pretendard-ExtraBold.subset.woff2",
      weight: "800",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning className={pretendard.variable}>
      <body className="antialiased">
        <Providers>
          <Header />
          <div className="flex">
            <Sidebar />
            <div className="flex flex-1 flex-col md:pl-[240px]">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
