export const menu = [
  {
    title: "theme",
    items: [
      { title: "Color", href: "/theme/color" },
      { title: "Typography", href: "/theme/typography" },
      { title: "Elevation", href: "/theme/elevation" },
    ],
  },
  {
    title: "components",
    items: [
      { title: "Button", href: "/components/button" },
      { title: "Icon Button", href: "/components/icon-button" },
      { title: "Input", href: "/components/input" },
      { title: "Select", href: "/components/select" },
      { title: "Checkbox", href: "/components/checkbox" },
      { title: "Radio Group", href: "/components/radio-group" },
      { title: "Date Picker", href: "/components/date-picker" },
      { title: "Switch", href: "/components/switch" },
      { title: "Textarea", href: "/components/textarea" },
      { title: "Tag", href: "/components/tag" },
      { title: "Chip", href: "/components/chip" },
      { title: "Chip Button", href: "/components/chip-button" },
      { title: "Avatar", href: "/components/avatar" },
      { title: "Dialog", href: "/components/dialog" },
      { title: "Prompt", href: "/components/prompt" },
      { title: "Bottom Sheet", href: "/components/bottom-sheet" },
      { title: "Badge", href: "/components/badge" },
      { title: "Tabs", href: "/components/tabs" },
      { title: "Skeleton", href: "/components/skeleton" },
      { title: "Dropdown Menu", href: "/components/dropdown-menu" },
      { title: "Popover", href: "/components/popover" },
      { title: "Tooltip", href: "/components/tooltip" },
      { title: "Pagination", href: "/components/pagination" },
      { title: "Fab", href: "/components/fab" },
      { title: "Form", href: "/components/form" },
      { title: "Chat", href: "/components/chat" },
    ],
  },
  {
    title: "desktop",
    items: [
      { title: "Feed", href: "/desktop/feed" },
      { title: "Chat", href: "/desktop/chat" },
      { title: "Settings", href: "/desktop/settings" },
      { title: "Login", href: "/desktop/login" },
    ],
  },
  {
    title: "mobile",
    items: [
      { title: "Apartments", href: "/mobile/apartments" },
      { title: "Permissions", href: "/mobile/permissions" },
      { title: "Terms", href: "/mobile/terms" },
      { title: "Landing", href: "/mobile/landing" },
      { title: "Community", href: "/mobile/community" },
      { title: "Products", href: "/mobile/products" },
      { title: "Search", href: "/mobile/search" },
    ],
  },
] as const;
